#!/usr/bin/env node

/**
 * Hedera MultiSig Initialization Wizard
 *
 * Interactive CLI wizard to set up a new multi-sig project.
 * Run with: npx @lazysuperheroes/hedera-multisig init
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const chalk = require('chalk');
const crypto = require('crypto');

// Configuration templates
const ENV_TEMPLATE = `# Hedera MultiSig Configuration
# Generated by hedera-multisig init

# Network Configuration
# Options: TEST, MAIN, PREVIEW
ENVIRONMENT={{NETWORK}}

# Operator Account (for paying transaction fees)
OPERATOR_ID={{OPERATOR_ID}}
OPERATOR_KEY={{OPERATOR_KEY}}

# Multi-Sig Server Configuration
MULTISIG_PORT={{PORT}}
MULTISIG_HOST=localhost

# Session Configuration
SESSION_TIMEOUT=1800000

# Logging
LOG_LEVEL=info

# Optional: Redis for session persistence
# REDIS_HOST=localhost
# REDIS_PORT=6379

# Optional: TLS Configuration
# TLS_CERT=./certs/server.crt
# TLS_KEY=./certs/server.key

# Optional: Tunnel for remote access
# NGROK_AUTH_TOKEN=your_token_here
`;

const GITIGNORE_TEMPLATE = `# Environment and secrets
.env
.env.*
!.env.example

# Encrypted key files
*.enc

# Logs
logs/
*.log

# Transaction exports
multisig-transactions/

# Session files
.multisig-session.json

# Node modules
node_modules/

# OS files
.DS_Store
Thumbs.db
`;

const PACKAGE_JSON_TEMPLATE = {
  name: "my-multisig-project",
  version: "1.0.0",
  description: "Multi-signature transaction management for Hedera",
  scripts: {
    "server": "hedera-multisig server",
    "participant": "hedera-multisig participant",
    "sign": "hedera-multisig sign",
    "keys:create": "hedera-multisig keys create",
    "keys:test": "hedera-multisig keys test",
    "audit": "hedera-multisig audit"
  },
  dependencies: {
    "@lazysuperheroes/hedera-multisig": "^1.1.0"
  }
};

const EXAMPLE_SCRIPT = `/**
 * Example: Multi-Sig Transfer
 *
 * Demonstrates a 2-of-3 multi-sig HBAR transfer using the interactive workflow.
 */

require('dotenv').config();

const {
  Client,
  TransferTransaction,
  Hbar,
  AccountId
} = require('@hashgraph/sdk');

const {
  WorkflowOrchestrator,
  PromptKeyProvider
} = require('@lazysuperheroes/hedera-multisig');

async function main() {
  // Initialize Hedera client
  const network = process.env.ENVIRONMENT || 'TEST';
  const client = network === 'MAIN' ? Client.forMainnet() : Client.forTestnet();

  // Set operator for fee payment
  client.setOperator(
    AccountId.fromString(process.env.OPERATOR_ID),
    process.env.OPERATOR_KEY
  );

  // Create the transfer transaction
  const senderAccount = '0.0.YOUR_MULTISIG_ACCOUNT';  // Replace with your account
  const recipientAccount = '0.0.RECIPIENT';            // Replace with recipient
  const amount = 10;                                   // HBAR to transfer

  const transaction = new TransferTransaction()
    .addHbarTransfer(senderAccount, Hbar.from(-amount))
    .addHbarTransfer(recipientAccount, Hbar.from(amount));

  // Create orchestrator
  const orchestrator = new WorkflowOrchestrator(client, {
    verbose: true,
    auditLogPath: './logs/audit.log'
  });

  console.log('\\n=== Multi-Sig Transfer ===');
  console.log(\`Sending \${amount} HBAR from \${senderAccount} to \${recipientAccount}\`);
  console.log('Threshold: 2 of 3 signatures required\\n');

  try {
    // Execute with 2-of-3 threshold
    const result = await orchestrator.execute(transaction, {
      workflow: 'interactive',
      keyProviders: [
        new PromptKeyProvider({ label: 'Signer 1' }),
        new PromptKeyProvider({ label: 'Signer 2' }),
        new PromptKeyProvider({ label: 'Signer 3' })
      ],
      threshold: 2,
      signerLabels: ['Alice', 'Bob', 'Charlie']
    });

    console.log('\\n=== Transaction Complete ===');
    console.log('Transaction ID:', result.transactionId);
    console.log('Status:', result.receipt.status.toString());

  } catch (error) {
    console.error('\\nTransaction failed:', error.message);
    process.exit(1);
  }
}

main();
`;

const NETWORKED_EXAMPLE = `/**
 * Example: Networked Multi-Sig Session
 *
 * Demonstrates setting up a networked signing session where
 * participants can be remote (CLI or browser-based).
 */

require('dotenv').config();

const {
  Client,
  TransferTransaction,
  Hbar,
  AccountId,
  PrivateKey
} = require('@hashgraph/sdk');

const {
  SigningSessionManager,
  MultiSigWebSocketServer
} = require('@lazysuperheroes/hedera-multisig');

async function main() {
  // Initialize Hedera client
  const network = process.env.ENVIRONMENT || 'TEST';
  const client = network === 'MAIN' ? Client.forMainnet() : Client.forTestnet();

  client.setOperator(
    AccountId.fromString(process.env.OPERATOR_ID),
    process.env.OPERATOR_KEY
  );

  // Define eligible signers (replace with your public keys)
  const eligiblePublicKeys = [
    'YOUR_PUBLIC_KEY_1',  // Replace with actual public keys
    'YOUR_PUBLIC_KEY_2',
    'YOUR_PUBLIC_KEY_3'
  ];

  // Create session manager
  const sessionManager = new SigningSessionManager(client, {
    verbose: true,
    autoExecute: false  // Manual execution after threshold met
  });

  // Create WebSocket server
  const wsServer = new MultiSigWebSocketServer(sessionManager, {
    port: parseInt(process.env.MULTISIG_PORT) || 3001,
    verbose: true
  });

  // Start server
  const serverInfo = await wsServer.start();
  console.log('\\n=== Multi-Sig Server Started ===');
  console.log('URL:', serverInfo.url);

  // Create pre-session (participants can join before transaction)
  const session = await sessionManager.createSession(null, {
    threshold: 2,
    eligiblePublicKeys,
    expectedParticipants: 3
  });

  console.log('\\n=== Session Created ===');
  console.log('Session ID:', session.sessionId);
  console.log('PIN:', session.pin);
  console.log('Threshold:', session.threshold, 'of', eligiblePublicKeys.length);

  console.log('\\n=== Share with Participants ===');
  console.log('Server URL:', serverInfo.url);
  console.log('Session ID:', session.sessionId);
  console.log('PIN:', session.pin);

  console.log('\\nWaiting for participants to connect...');
  console.log('Press Ctrl+C to stop the server.\\n');

  // Handle shutdown
  process.on('SIGINT', async () => {
    console.log('\\nShutting down...');
    await wsServer.stop();
    sessionManager.shutdown();
    process.exit(0);
  });
}

main().catch(console.error);
`;

class InitWizard {
  constructor() {
    this.rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    this.config = {};
  }

  async run() {
    console.log(chalk.bold.cyan('\n╔════════════════════════════════════════════════════════════╗'));
    console.log(chalk.bold.cyan('║          Hedera MultiSig Initialization Wizard             ║'));
    console.log(chalk.bold.cyan('╚════════════════════════════════════════════════════════════╝\n'));

    console.log(chalk.gray('This wizard will help you set up a new multi-sig project.\n'));

    try {
      // Step 1: Project directory
      await this.promptProjectDir();

      // Step 2: Network selection
      await this.promptNetwork();

      // Step 3: Operator account
      await this.promptOperator();

      // Step 4: Server configuration
      await this.promptServerConfig();

      // Step 5: Security options
      await this.promptSecurityOptions();

      // Create project
      await this.createProject();

      this.showSuccess();

    } catch (error) {
      if (error.message === 'cancelled') {
        console.log(chalk.yellow('\n\nSetup cancelled.\n'));
      } else {
        console.error(chalk.red('\nError:'), error.message);
      }
      process.exit(1);
    } finally {
      this.rl.close();
    }
  }

  prompt(question, defaultValue = '') {
    return new Promise((resolve) => {
      const defaultText = defaultValue ? chalk.gray(` (${defaultValue})`) : '';
      this.rl.question(chalk.white(question) + defaultText + chalk.white(': '), (answer) => {
        resolve(answer.trim() || defaultValue);
      });
    });
  }

  async promptYesNo(question, defaultYes = true) {
    const defaultText = defaultYes ? 'Y/n' : 'y/N';
    const answer = await this.prompt(`${question} [${defaultText}]`);
    if (!answer) return defaultYes;
    return answer.toLowerCase().startsWith('y');
  }

  async promptProjectDir() {
    console.log(chalk.bold('📁 Project Setup\n'));

    const cwd = process.cwd();
    const currentDir = path.basename(cwd);

    const useCurrentDir = await this.promptYesNo(
      `Create project in current directory (${currentDir})?`,
      true
    );

    if (useCurrentDir) {
      this.config.projectDir = cwd;
      this.config.projectName = currentDir;
    } else {
      const dirName = await this.prompt('Project directory name', 'my-multisig');
      this.config.projectDir = path.join(cwd, dirName);
      this.config.projectName = dirName;
    }

    console.log(chalk.green(`  ✓ Project directory: ${this.config.projectDir}\n`));
  }

  async promptNetwork() {
    console.log(chalk.bold('🌐 Network Configuration\n'));

    console.log('  1. Testnet (recommended for development)');
    console.log('  2. Mainnet (production)');
    console.log('  3. Previewnet (experimental features)\n');

    const choice = await this.prompt('Select network [1-3]', '1');

    switch (choice) {
      case '2':
        this.config.network = 'MAIN';
        break;
      case '3':
        this.config.network = 'PREVIEW';
        break;
      default:
        this.config.network = 'TEST';
    }

    console.log(chalk.green(`  ✓ Network: ${this.config.network}\n`));
  }

  async promptOperator() {
    console.log(chalk.bold('👤 Operator Account (for transaction fees)\n'));

    console.log(chalk.gray('  The operator account pays transaction fees.'));
    console.log(chalk.gray('  This is NOT the multi-sig account.\n'));

    this.config.operatorId = await this.prompt('Operator Account ID (e.g., 0.0.12345)');

    if (!this.config.operatorId.match(/^\d+\.\d+\.\d+$/)) {
      console.log(chalk.yellow('  ⚠ Invalid account ID format, using placeholder'));
      this.config.operatorId = '0.0.YOUR_OPERATOR_ID';
    }

    const hasKey = await this.promptYesNo('Do you have the operator private key ready?', false);

    if (hasKey) {
      this.config.operatorKey = await this.prompt('Operator Private Key');
      if (!this.config.operatorKey) {
        this.config.operatorKey = 'YOUR_OPERATOR_KEY';
      }
    } else {
      this.config.operatorKey = 'YOUR_OPERATOR_KEY';
      console.log(chalk.gray('  You can add the key to .env later.'));
    }

    console.log(chalk.green(`  ✓ Operator: ${this.config.operatorId}\n`));
  }

  async promptServerConfig() {
    console.log(chalk.bold('🖥️  Server Configuration\n'));

    this.config.port = await this.prompt('WebSocket server port', '3001');

    if (isNaN(parseInt(this.config.port))) {
      this.config.port = '3001';
    }

    console.log(chalk.green(`  ✓ Port: ${this.config.port}\n`));
  }

  async promptSecurityOptions() {
    console.log(chalk.bold('🔒 Security Options\n'));

    this.config.createKeyDir = await this.promptYesNo('Create keys/ directory for encrypted key files?', true);
    this.config.createLogsDir = await this.promptYesNo('Create logs/ directory for audit logs?', true);
    this.config.createExamples = await this.promptYesNo('Create example scripts?', true);

    console.log();
  }

  async createProject() {
    console.log(chalk.bold('📦 Creating Project...\n'));

    // Create project directory if needed
    if (!fs.existsSync(this.config.projectDir)) {
      fs.mkdirSync(this.config.projectDir, { recursive: true });
      console.log(chalk.gray(`  Created ${this.config.projectDir}`));
    }

    // Create .env file
    const envContent = ENV_TEMPLATE
      .replace('{{NETWORK}}', this.config.network)
      .replace('{{OPERATOR_ID}}', this.config.operatorId)
      .replace('{{OPERATOR_KEY}}', this.config.operatorKey)
      .replace('{{PORT}}', this.config.port);

    fs.writeFileSync(
      path.join(this.config.projectDir, '.env'),
      envContent
    );
    console.log(chalk.green('  ✓ Created .env'));

    // Create .env.example (without sensitive data)
    const envExample = ENV_TEMPLATE
      .replace('{{NETWORK}}', 'TEST')
      .replace('{{OPERATOR_ID}}', '0.0.YOUR_ACCOUNT_ID')
      .replace('{{OPERATOR_KEY}}', 'YOUR_PRIVATE_KEY')
      .replace('{{PORT}}', '3001');

    fs.writeFileSync(
      path.join(this.config.projectDir, '.env.example'),
      envExample
    );
    console.log(chalk.green('  ✓ Created .env.example'));

    // Create .gitignore
    fs.writeFileSync(
      path.join(this.config.projectDir, '.gitignore'),
      GITIGNORE_TEMPLATE
    );
    console.log(chalk.green('  ✓ Created .gitignore'));

    // Create package.json
    const packageJson = { ...PACKAGE_JSON_TEMPLATE };
    packageJson.name = this.config.projectName;

    fs.writeFileSync(
      path.join(this.config.projectDir, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );
    console.log(chalk.green('  ✓ Created package.json'));

    // Create directories
    if (this.config.createKeyDir) {
      const keysDir = path.join(this.config.projectDir, 'keys');
      if (!fs.existsSync(keysDir)) {
        fs.mkdirSync(keysDir);
        fs.writeFileSync(
          path.join(keysDir, '.gitkeep'),
          '# This directory stores encrypted key files\n'
        );
      }
      console.log(chalk.green('  ✓ Created keys/'));
    }

    if (this.config.createLogsDir) {
      const logsDir = path.join(this.config.projectDir, 'logs');
      if (!fs.existsSync(logsDir)) {
        fs.mkdirSync(logsDir);
        fs.writeFileSync(
          path.join(logsDir, '.gitkeep'),
          '# This directory stores audit logs\n'
        );
      }
      console.log(chalk.green('  ✓ Created logs/'));
    }

    // Create examples
    if (this.config.createExamples) {
      const examplesDir = path.join(this.config.projectDir, 'examples');
      if (!fs.existsSync(examplesDir)) {
        fs.mkdirSync(examplesDir);
      }

      fs.writeFileSync(
        path.join(examplesDir, 'transfer.js'),
        EXAMPLE_SCRIPT
      );
      console.log(chalk.green('  ✓ Created examples/transfer.js'));

      fs.writeFileSync(
        path.join(examplesDir, 'networked-session.js'),
        NETWORKED_EXAMPLE
      );
      console.log(chalk.green('  ✓ Created examples/networked-session.js'));
    }

    console.log();
  }

  showSuccess() {
    console.log(chalk.bold.green('╔════════════════════════════════════════════════════════════╗'));
    console.log(chalk.bold.green('║                    Setup Complete! 🎉                      ║'));
    console.log(chalk.bold.green('╚════════════════════════════════════════════════════════════╝\n'));

    console.log(chalk.bold('Next Steps:\n'));

    if (this.config.projectDir !== process.cwd()) {
      console.log(chalk.cyan(`  1. cd ${path.relative(process.cwd(), this.config.projectDir)}`));
      console.log(chalk.cyan('  2. npm install'));
    } else {
      console.log(chalk.cyan('  1. npm install'));
    }

    console.log(chalk.cyan('  3. Edit .env with your operator credentials'));
    console.log(chalk.cyan('  4. Create encrypted key files:'));
    console.log(chalk.gray('     npx hedera-multisig keys create'));
    console.log(chalk.cyan('  5. Start the server:'));
    console.log(chalk.gray('     npm run server -- --threshold 2 --keys "key1,key2,key3"'));

    console.log(chalk.bold('\nUseful Commands:\n'));
    console.log('  ' + chalk.yellow('npm run server') + '        - Start multi-sig server');
    console.log('  ' + chalk.yellow('npm run participant') + '   - Join a session');
    console.log('  ' + chalk.yellow('npm run keys:create') + '   - Create encrypted key file');
    console.log('  ' + chalk.yellow('npm run audit') + '         - Run security audit');

    console.log(chalk.bold('\nDocumentation:\n'));
    console.log('  ' + chalk.blue('https://github.com/lazysuperheroes/hedera-multisig'));

    console.log();
  }
}

// Run the wizard
const wizard = new InitWizard();
wizard.run();
