#!/usr/bin/env node
/**
 * Walkthrough setup: generate three Ed25519 signing keys for the
 * contract walkthrough.
 *
 * Writes (per signer):
 *   walkthrough-keys.{alice,bob,carol}.encrypted  — AES-256-GCM encrypted
 *                                                    (RECOMMENDED — what
 *                                                    `participant --keyfile`
 *                                                    expects in production)
 *
 * Plus an internal plaintext index used by other walkthrough scripts:
 *   walkthrough-keys.json  — { keys: { alice, bob, carol } }, used by
 *                            01-create-demo-eoa.js (alice public key) and
 *                            05-convert-eoa-to-multisig.js (which signs
 *                            locally with all three private keys; this is
 *                            a walkthrough convenience — production
 *                            multi-sig conversions distribute the new-key
 *                            signing across signers).
 *
 * Encryption passphrase: WALKTHROUGH_PASSPHRASE constant below. The
 * `EncryptedFileProvider` requires ≥12 chars; we use a fixed value so the
 * walkthrough README can reference it. **For testnet only.** A real
 * production deployment generates each key on a separate device by a
 * separate person, with a strong passphrase per signer.
 *
 * If you've already generated keys via the HBAR walkthrough and want to
 * reuse them, copy the files directly:
 *   cp ../walkthrough-hbar/walkthrough-keys.* .
 * Otherwise this script gives you a fresh, fully-encapsulated set.
 */

const fs = require('fs');
const path = require('path');
const { PrivateKey } = require('@hashgraph/sdk');
const chalk = require('chalk');
const EncryptedFileProvider = require('../../keyManagement/EncryptedFileProvider');

const SIGNERS = ['alice', 'bob', 'carol'];
const OUT_DIR = __dirname;

// Documented in README — testnet only, ≥12 chars to satisfy EncryptedFileProvider.
const WALKTHROUGH_PASSPHRASE = 'walkthrough-test';

function main() {
  console.log(chalk.bold.cyan('\n━━━ Generate signing keys (contract walkthrough) ━━━\n'));

  const keys = {};
  for (const name of SIGNERS) {
    const priv = PrivateKey.generateED25519();
    keys[name] = {
      privateKey: priv.toString(),
      publicKey: priv.publicKey.toString(),
    };

    // Encrypted per-signer file (single-key array — what
    // EncryptedFileProvider.createEncryptedFile expects, what
    // participant.js consumes via `--keyfile`)
    const encryptedPath = path.join(OUT_DIR, `walkthrough-keys.${name}.encrypted`);
    EncryptedFileProvider.createEncryptedFile(
      [priv.toString()],
      WALKTHROUGH_PASSPHRASE,
      encryptedPath,
      { description: `walkthrough-contract testnet key (${name})` }
    );

    console.log(chalk.green('✓'), chalk.bold(name.padEnd(8)), priv.publicKey.toString().slice(0, 24) + '…');
  }

  // Combined plaintext index — used internally by 01-create-demo-eoa.js
  // (public key for alice) and 05-convert-eoa-to-multisig.js (private keys
  // for the dual-signature account-update). Not consumed by the CLI
  // participant flow.
  const combinedPath = path.join(OUT_DIR, 'walkthrough-keys.json');
  fs.writeFileSync(combinedPath, JSON.stringify({
    note: 'TESTNET ONLY — generated by examples/walkthrough-contract/setup-keys.js. Do not commit. Do not reuse on mainnet.',
    generatedAt: new Date().toISOString(),
    passphrase: WALKTHROUGH_PASSPHRASE,
    keys,
  }, null, 2));

  console.log(chalk.bold.green('\n✅ Keys written:'));
  console.log(chalk.gray('   Encrypted (recommended for participant flow):'));
  for (const name of SIGNERS) {
    console.log(chalk.gray(`     ${path.join(OUT_DIR, `walkthrough-keys.${name}.encrypted`)}`));
  }
  console.log(chalk.gray('   Plaintext index (internal use by walkthrough scripts):'));
  console.log(chalk.gray(`     ${combinedPath}`));

  console.log(chalk.bold.white(`\n   Passphrase: ${chalk.cyan(WALKTHROUGH_PASSPHRASE)}`));
  console.log(chalk.gray('   (Documented constant — testnet walkthrough only)'));

  console.log(chalk.yellow('\n⚠  Testnet keys. Delete after the walkthrough — they are gitignored but'));
  console.log(chalk.yellow('   should never be committed or reused on mainnet.'));

  console.log(chalk.bold.cyan('\nNext: node 00-precheck.js\n'));
}

main();
